### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(4, 5, 3)

array([[[0.36654859, 0.84879874, 0.1327417 ],
        [0.74289699, 0.36706153, 0.17757072],
        [0.66553741, 0.28859781, 0.1765332 ],
        [0.56200997, 0.59644785, 0.18565935],
        [0.00149148, 0.22916046, 0.71376409]],

       [[0.28274575, 0.3953965 , 0.85132207],
        [0.75049913, 0.79757611, 0.18109221],
        [0.18513671, 0.49398551, 0.18743514],
        [0.76644431, 0.85067521, 0.5200303 ],
        [0.57579289, 0.98810827, 0.98996079]],

       [[0.90003642, 0.24157563, 0.70034641],
        [0.01528775, 0.08201425, 0.39805176],
        [0.37177616, 0.79250684, 0.19865083],
        [0.99071641, 0.54486696, 0.4147566 ],
        [0.96772063, 0.12125159, 0.15491354]],

       [[0.70457493, 0.70864055, 0.7728215 ],
        [0.31377711, 0.43655237, 0.28941543],
        [0.41187009, 0.19464471, 0.71145867],
        [0.76315598, 0.26688901, 0.33918403],
        [0.531328  , 0.81258893, 0.73831584]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [3]:
np.random.randn(5)

array([-0.023723  ,  0.48633239, -1.59859353,  0.77714023, -0.66916669])

In [4]:
np.random.randn(3, 4, 2)

array([[[-0.23659867,  1.36808164],
        [ 0.31692359, -0.09393809],
        [-1.15562006,  1.52453898],
        [ 0.9448703 ,  1.08148519]],

       [[ 0.75697536,  0.64254274],
        [-2.21069927, -1.06647282],
        [-1.41357424,  0.03470425],
        [ 0.63513839, -0.75569167]],

       [[-0.27794283,  0.2798904 ],
        [ 1.31608962,  0.27849674],
        [ 0.01482531, -0.58220529],
        [-0.37698612,  0.35384169]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [5]:
np.random.randint(1, 100, size=(5,))

array([24, 28, 25, 88, 82])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [6]:
np.random.seed(23)
np.random.randn(3, 4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [7]:
np.random.choice(100, size=(3, 4))

array([[79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1]])

In [8]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[1. , 2. ],
       [3. , 4.9]])

In [12]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2),replace=False)

array([[2. , 1.5],
       [2.6, 3. ]])