## 학습목표
 1. 브로드캐스팅의 이해

In [2]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.50025817 0.45754636 0.17051081 0.72669489 0.83229467]
 [0.48888192 0.54307131 0.87141449 0.2854348  0.74484795]
 [0.11435867 0.44674846 0.12256943 0.20032605 0.25382575]]


In [4]:
x * y

array([[0.        , 0.45754636, 0.34102162, 2.18008468, 3.32917868],
       [2.44440959, 3.25842788, 6.09990141, 2.28347843, 6.70363158],
       [1.14358671, 4.91423306, 1.4708331 , 2.60423866, 3.55356043]])

* Scalar(상수)와의 연산

In [5]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [10]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print('a',a.shape)
print('b',b.shape)
print('c',c.shape)
print('d',d.shape)
print(d)

a (4, 3)
b (3,)
c (4,)
d (1, 3)
[[100 101 102]]


In [11]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
print(b)

[100 101 102]


In [13]:
print(c)

[1000 1001 1002 1003]


In [14]:
print(d)

[[100 101 102]]


In [7]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [8]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [9]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])