In [1]:
import numpy as np

In [2]:
x = [[25,1,2,1],
    [20,0,0,2],
    [8,1,1,5],
    [15,1,0,2],
    [35,0,3,1],
    [40,0,5,4]]

x = np.array(x)

In [4]:
w = [0.3,0.2,0.5,0.1]
b = 0.1

w*x

array([[ 7.5,  0.2,  1. ,  0.1],
       [ 6. ,  0. ,  0. ,  0.2],
       [ 2.4,  0.2,  0.5,  0.5],
       [ 4.5,  0.2,  0. ,  0.2],
       [10.5,  0. ,  1.5,  0.1],
       [12. ,  0. ,  2.5,  0.4]])

In [7]:
np.sum(w*x, axis=1), np.dot(x,w)

(array([ 8.8,  6.2,  3.6,  4.9, 12.1, 14.9]),
 array([ 8.8,  6.2,  3.6,  4.9, 12.1, 14.9]))

In [8]:
np.sum(w*x, axis=1)+b, np.dot(x,w)+b

(array([ 8.9,  6.3,  3.7,  5. , 12.2, 15. ]),
 array([ 8.9,  6.3,  3.7,  5. , 12.2, 15. ]))

In [9]:
y_hat = np.sum(x*w, axis=1) + b

In [14]:
x = [[25,1,2,1],
    [20,0,0,2],
    [8,1,1,5],
    [15,1,0,2],
    [35,0,3,1],
    [40,0,5,4]]

x = np.array(x)

# Dense
w = [[0.3,0.1],
    [0.2,0.7],
    [0.5,0.4],
    [0.1,0.1]]
b = [0.1,0.7]

w = np.array(w)
b = np.array(b)

y_hat0 = np.sum(x*w[:,0], axis=1) + b[0]
y_hat1 = np.sum(x*w[:,1], axis=1) + b[1]


In [17]:
x = [[25,1,2,1],
    [20,0,0,2],
    [8,1,1,5],
    [15,1,0,2],
    [35,0,3,1],
    [40,0,5,4]]

x = np.array(x)

# Dense
# ReLU 적용
# ReLU함수는 맨 마지막 출력층을 제외한 모든곳에 사용을 권장
w = [[-0.3,0.1],
    [0.2,0.7],
    [0.5,0.4],
    [0.1,0.1]]
b = [0.1,0.7]

w = np.array(w)
b = np.array(b)

y_hat0 = np.sum(x*w[:,0], axis=1) + b[0]
y_hat1 = np.sum(x*w[:,1], axis=1) + b[1]

y_hat0[y_hat0<0] = 0
y_hat1[y_hat1<0] = 0

y_hat0, y_hat1

(array([0., 0., 0., 0., 0., 0.]), array([4.8, 2.9, 3.1, 3.1, 5.5, 7.1]))

In [20]:
x = []
for x1,x2 in zip(y_hat0,y_hat1):
    x.append([])
    x[-1].append(x1)
    x[-1].append(x2)

x

[[0.0, 4.8],
 [0.0, 2.9000000000000004],
 [0.0, 3.0999999999999996],
 [0.0, 3.1000000000000005],
 [0.0, 5.5],
 [0.0, 7.1000000000000005]]

In [ ]:
w = [[1,2,3,4,5],
    [2,3,1,1,3]]
b = [1,2,3,4,5]

w = np.array(w)
b = np.array(b)

y_hat0 = x*w[:,0] * b[0]
y_hat0 = x*w[:,1] * b[1]
y_hat0 = x*w[:,2] * b[2]
y_hat0 = x*w[:,3] * b[3]
y_hat0 = x*w[:,4] * b[4]

y_hat0[y_hat0<0] = 0
y_hat1[y_hat1<0] = 0
y_hat2[y_hat2<0] = 0
y_hat3[y_hat3<0] = 0
y_hat4[y_hat4<0] = 0

In [21]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [22]:
x=np.array([1,2,3,4,5,6])
y=np.array([10,98,8,2,3,4])

In [23]:
tf.random.set_seed(1234)

In [24]:
input_layer = tf.keras.layers.InputLayer(input_shape=(1,))
hidden_layer1 = tf.keras.layers.Dense(units=4, activation='relu')
hidden_layer2 = tf.keras.layers.Dense(units=2, activation='relu')
output_layer= tf.keras.layers.Dense(units=1)
# activation이 없으면 활성화함수 wx+b가 되어있는 것임.
model = keras.Sequential([
input_layer,
hidden_layer1,
hidden_layer2,
output_layer
])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 8         
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [26]:
modelvalues = model.weights
modelvalues

[<tf.Variable 'dense/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[-0.29656547, -0.326016  ,  0.10595298, -0.23667526]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.50212336, -0.16338134],
        [-0.8829603 ,  0.23382974],
        [ 0.05000877,  0.30985618],
        [ 0.8955786 ,  0.27770996]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.07074404],
        [-1.097157  ]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [27]:
model.layers

In [29]:
tmp = tf.keras.Model(inputs=model.input, outputs=model.layers[0].output)
tmp(x)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[0.        , 0.        , 0.10595298, 0.        ],
       [0.        , 0.        , 0.21190596, 0.        ],
       [0.        , 0.        , 0.31785893, 0.        ],
       [0.        , 0.        , 0.4238119 , 0.        ],
       [0.        , 0.        , 0.5297649 , 0.        ],
       [0.        , 0.        , 0.63571787, 0.        ]], dtype=float32)>

In [30]:
wList = model.weights[0]
bList = model.weights[1]
x*wList[0][0] + bList[0]

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([-0.29656547, -0.59313095, -0.8896964 , -1.1862619 , -1.4828274 ,
       -1.7793928 ], dtype=float32)>